const cards = [
  {
    title: "card1",
    subTitle: "sub card 1",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny1@gmail.com",
    image: {
      url: "assets/home1.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card2",
    subTitle: "sub card 2",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny2@gmail.com",
    image: {
      url: "assets/home2.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card3",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny3@gmail.com",
    image: {
      url: "assets/home3.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card4",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny4@gmail.com",
    image: {
      url: "assets/home4.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card5",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny5@gmail.com",
    image: {
      url: "assets/slide1.png",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card6",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny6@gmail.com",
    image: {
      url: "assets/slide3.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card7",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny7@gmail.com",
    image: {
      url: "assets/slide2.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card8",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny8@gmail.com",
    image: {
      url: "assets/u1.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card9",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny9@gmail.com",
    image: {
      url: "assets/u6.png",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card10",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny10@gmail.com",
    image: {
      url: "assets/u3.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card11",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny11@gmail.com",
    image: {
      url: "assets/u4.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
  {
    title: "card12",
    subTitle: "sub card 3",
    description: "save the card pls",
    phone: "0500000000",
    email: "kenny12@gmail.com",
    image: {
      url: "assets/u7.jpg",
      alt: "alalla",
    },
    address: {
      country: "Israel",
      city: "Ashkeluna",
      street: "jump street",
      houseNumber: 23,
      zip: 0,
    },
  },
];

module.exports = cards;
